export enum ContractStatus {
  PENDING_VOLUNTEER = 'PENDING_VOLUNTEER',
  PENDING_ADMIN = 'PENDING_ADMIN',
  NOT_STARTED = 'NOT_STARTED',
  CLOSED = 'CLOSED',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
}
