on:
  push:
    branches:
      - main
      - 'ci/update-workflow'
    tags:
      - 'v*'
    paths:
      - 'backend/**'
  workflow_dispatch:

name: Build Docker image

jobs:

  build:
    name: Build Docker image
    uses: code4romania/.github/.github/workflows/build-push-image-ecr.yml@main
    with:
      image_name: vic
      region: eu-west-1
      context: backend
      tags: |
        type=edge
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
    secrets:
      role_to_assume: ${{ secrets.ROLE_TO_ASSUME }}
